export const COLOURS = {
	LIGHT: '#ffffff',
	DARK: '#141414',
	BLACK: '#000000',
	GRADIENT_ONE: {
		FIRST: '#FFA99F',
		SECOND: '#FFE29F'
	},
	GRADIENT_TWO: {
		FIRST: '#FFBBEC',
		SECOND: '#A9C9FF'
	},
	GRADIENT_THREE: {
		FIRST: '#37ECBA',
		SECOND: '#8FD3F4'
	}
}
